### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by bnigrovic** [stat231-f21/blog_data-ballers#1]
# 1. Ideas

### Do you plan for your final project to be an extension of the mid-semester project? If Yes: Identify specific ideas for how you will extend your mid-semester project. The more details the better here. Do you plan to add additional data? Be sure to include which topic(s) you will incorporate: text analysis, network science, unsupervised learning, and/or spatial data.

Yes, we plan to extend our mid-semester project. For reference, our Shiny app <https://bnigrovic.shinyapps.io/NBAcomparisons-BenTylerKedar/> offered users a general tool for comparing players, teams, and overall gameplay across different eras of the NBA (1995/96 vs. 2015/16). We believe that while we successfully met our goal of helping basketball fans answer debates, we could go a lot farther. Specifically, we hope to go much deeper into the player and team analysis aspect of our project. Our original Shiny app offered users a basic display of different players — including basic stats such as minutes per game, points, and assists. However, the display did not effectively reveal that much information about play style, effectiveness, and performance that users could not see by just looking at a player’s box score. Our blog project hopes to extend this analysis to construct cool visualizations that offer unique perspectives on different players and teams who we admire. One critical component of these comparisons involves spatial data. To achieve this end, we will need to scrape and wrangle new data for this project that includes information about the shot location of every shot for each player and team interest. We plan to overlay player and team shots onto a basketball court (scatterplot and volcano plots). These visualizations will offer player insights such as shot selection, points per shot, and comparisons between the selected player and the league average. In this way, we will better understand how the best players in the NBA play the game of basketball. Notably, we plan to focus our analysis on the 2015/16 NBA season because there is no data about every shot from the 1995/96 season. Indeed, there is a much higher level of data collection today than even 20 years ago.

# 2. Plans

### Describe what you hope to deliver as a final product. Will your blog include a published Shiny application? Will it incorporate an interactive map? Will it involve a predictive model that forecasts future values of some quantity using data that you’ve integrated?

Since we have decided to extend our Shiny App with our blog, we will be incorporating some visuals of our app. However, we hope to go far beyond what our Shiny app visuals can provide. First, we will include improved versions of some of our visuals (e.g. adding hover features, more descriptive widgets, etc). These are important as they help to indicate the relationships between different shots taken and points scored (arguably the most important indicator for the success of a team as well as an individual player). This way, we can build off these visuals with an interactive map.
We hope to be able to include a map to display shot selection of specific players. If, perhaps, a reader was interested in a certain player (given a dropdown menu), it is our goal that they can choose a player and have that player’s shots over the course of the season displayed on a 2D map of a basketball court. We intend to use different skills learned over the last few weeks to achieve this, like mapping, but more importantly clustering. One idea we have discussed is using clustering to be able to group our spatial data into specific clusters to categorize different shots, and therefore be able to draw conclusions on which shots are most effective in the game. Now that we have data about shot distance, we will extend out analysis beyond just two point versus three point attempts. We plan to graph the distribution of shots by distance from the basket and the effectiveness of each shot at each distance from the basket. We might also do this for individual players and teams. 

# 3. Plans

### Outline a schedule for your group's progress that will take you from now (ideas phase) to final blog post and presentation at the end of the semester. During the last project, we had specific checkpoints for different phases of the project. Based on what you envision for your final blog post, identify checkpoints for your group and dates by which you plan to reach those checkpoints. Hold each other accountable, so you’re not waiting until the last minute to do things! In particular, you should have at least one checkpoint each week (ideally two) identifying what work you expect to complete by then.

Date | What needs to be done
November 6th (Maybe Nov. 9th if data is harder to wrangle than we expect) | Wrangle any additional data we want/need
November 9th | Assign/organize how we are going to break up the work
November 16th | Update shiny app
November 20th | Complete rough draft of R markdown file
December 3rd | Complete final draft of R markdown file
December 5th | Outline presentation
December 9th | Be ready for the presentation

**Comment by bebailey** [comment]
Have you figured out a way to get the shot location data? If it's a critical-but-impossible (given time constraints) part, what is your Plan B?

This was not part of the requirement, but please make sure you discuss amongst yourselves exactly how you plan to divide up the work (looks like you plan to do that later). Perhaps it would be useful to write it down as a sort of group contract, even. To the degree possible, we want equitable contributions to the core components of the blog, with flexibility for any individual to go "above and beyond" on any particular aspect of interest to them. 

---

To embed a shiny app, you can use a code chunk (see [this link](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) for details):

```
knitr::include_app("https://your-account.shinyapps.io/your-app/", height = "600px")
```
